config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'
  
  devise_for :admins
  mount_devise_token_auth_for 'User', at: 'users/auth', controllers: {
    sessions: "overrides/sessions",
    registrations: "overrides/registrations"
  }

  scope module: 'admin' do

    resources :user_profiles do
      collection do
        get :send_confirmation_token
      end
    end

    resources :orders do
      collection do
        #post :confirm
        get :confirm
        post :set_status
      end
    end

    namespace :product do
      resources :products
      resources :types
      resources :categories
      resources :complements
      resources :variations
      resources :ingredients
    end
  end

  namespace :user do

    resources :user_profiles
    resources :orders
    resources :addresses

    resources :register do
      collection do        
        post :check_telephone, :check_token, :confirm_token
      end  
    end

    resources :carts do
      collection do        
        post :add, :update_item, :remove, :checkout, :repurchase
      end  
    end

    scope module: 'payment_method' do
      resources :pagarmes
    end

    scope module: 'product' do
      resources :products
      resources :types
      resources :categories
      resources :complements
      resources :variations
      resources :ingredients      
    end
  end

  namespace :home do
    get 'admin/index'
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'inicio', to: 'home/admin#index'
  root to: 'home/admin#index'
end

app/controllers/admin/product/categories_controller.rb
class Admin::Product::CategoriesController < AdminController
  before_action :set_product_category, only: [:show, :edit, :update, :destroy]  

  # GET /product/categories
  # GET /product/categories.json
  def index
    @product_categories = Product::Category.all
  end

  # GET /product/categories/1
  # GET /product/categories/1.json
  def show
  end

  # GET /product/categories/new
  def new
    @product_category = Product::Category.new
  end

  # GET /product/categories/1/edit
  def edit
  end

  # POST /product/categories
  # POST /product/categories.json
  def create
    @product_category = Product::Category.new(product_category_params)

    respond_to do |format|
      if @product_category.save
        format.html { redirect_to @product_category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @product_category }
      else
        format.html { render :new }
        format.json { render json: @product_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product/categories/1
  # PATCH/PUT /product/categories/1.json
  def update
    respond_to do |format|
      if @product_category.update(product_category_params)
        format.html { redirect_to @product_category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_category }
      else
        format.html { render :edit }
        format.json { render json: @product_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product/categories/1
  # DELETE /product/categories/1.json
  def destroy
    @product_category.destroy
    respond_to do |format|
      format.html { redirect_to product_categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_category
      @product_category = Product::Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_category_params
      params.require(:product_category).permit(:name)
    end
end

app/controllers/admin/product/complements_controller.rb
class Admin::Product::ComplementsController < ApplicationController
  before_action :set_product_complement, only: [:show, :edit, :update, :destroy]

  # GET /product/complements
  # GET /product/complements.json
  def index
    @product_complements = Product::Complement.all
  end

  # GET /product/complements/1
  # GET /product/complements/1.json
  def show
  end

  # GET /product/complements/new
  def new
    @product_complement = Product::Complement.new
  end

  # GET /product/complements/1/edit
  def edit
  end

  # POST /product/complements
  # POST /product/complements.json
  def create
    @product_complement = Product::Complement.new(product_complement_params)

    respond_to do |format|
      if @product_complement.save
        format.html { redirect_to @product_complement, notice: 'Complement was successfully created.' }
        format.json { render :show, status: :created, location: @product_complement }
      else
        format.html { render :new }
        format.json { render json: @product_complement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product/complements/1
  # PATCH/PUT /product/complements/1.json
  def update
    respond_to do |format|
      if @product_complement.update(product_complement_params)
        format.html { redirect_to @product_complement, notice: 'Complement was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_complement }
      else
        format.html { render :edit }
        format.json { render json: @product_complement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product/complements/1
  # DELETE /product/complements/1.json
  def destroy
    @product_complement.destroy
    respond_to do |format|
      format.html { redirect_to product_complements_url, notice: 'Complement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_complement
      @product_complement = Product::Complement.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_complement_params
      params.require(:product_complement).permit(:name, :description, :price)
    end
end

app/controllers/admin/product/ingredients_controller.rb
class Admin::Product::IngredientsController < ApplicationController
  before_action :set_product_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /product/ingredients
  # GET /product/ingredients.json
  def index
    @product_ingredients = Product::Ingredient.all
  end

  # GET /product/ingredients/1
  # GET /product/ingredients/1.json
  def show
  end

  # GET /product/ingredients/new
  def new
    @product_ingredient = Product::Ingredient.new
  end

  # GET /product/ingredients/1/edit
  def edit
  end

  # POST /product/ingredients
  # POST /product/ingredients.json
  def create
    @product_ingredient = Product::Ingredient.new(product_ingredient_params)

    respond_to do |format|
      if @product_ingredient.save
        format.html { redirect_to @product_ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render :show, status: :created, location: @product_ingredient }
      else
        format.html { render :new }
        format.json { render json: @product_ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product/ingredients/1
  # PATCH/PUT /product/ingredients/1.json
  def update
    respond_to do |format|
      if @product_ingredient.update(product_ingredient_params)
        format.html { redirect_to @product_ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_ingredient }
      else
        format.html { render :edit }
        format.json { render json: @product_ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product/ingredients/1
  # DELETE /product/ingredients/1.json
  def destroy
    @product_ingredient.destroy
    respond_to do |format|
      format.html { redirect_to product_ingredients_url, notice: 'Ingredient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_ingredient
      @product_ingredient = Product::Ingredient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_ingredient_params
      params.require(:product_ingredient).permit(:name, :description, :price)
    end
end

app/controllers/admin/product/products_controller.rb
class Admin::Product::ProductsController < AdminController
  before_action :set_product_product, only: [:show, :edit, :update, :destroy]
  before_action :set_product_categories, only: [:new, :edit]
  before_action :set_product_types, only: [:new, :edit]  

  # GET /product/products
  # GET /product/products.json
  def index
    #@product_products = Product::Product.all
    @product_products = Product::Product.all.order(updated_at: :desc).paginate(:page => params[:page], :per_page => 10)
    #@product_products = Product::Product.all.paginate(:page => params[:page], :per_page => 10)
  end

  # GET /product/products/1
  # GET /product/products/1.json
  def show
  end

  # GET /product/products/new
  def new
    @product_product = Product::Product.new
  end

  # GET /product/products/1/edit
  def edit
  end

  # POST /product/products
  # POST /product/products.json
  def create
    @product_product = Product::Product.new(product_product_params)

    respond_to do |format|
      if @product_product.save
        format.html { redirect_to @product_product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product_product }
      else
        format.html { render :new }
        format.json { render json: @product_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product/products/1
  # PATCH/PUT /product/products/1.json
  def update
    respond_to do |format|
      if @product_product.update(product_product_params)
        format.html { redirect_to @product_product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_product }
      else
        format.html { render :edit }
        format.json { render json: @product_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product/products/1
  # DELETE /product/products/1.json
  def destroy
    @product_product.destroy
    respond_to do |format|
      format.html { redirect_to product_products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_product
      @product_product = Product::Product.find(params[:id])
    end

    def set_product_categories
      @product_categories = Product::Category.all.pluck(:name, :id)
    end
  
    def set_product_types
      @product_types = Product::Type.all.pluck(:name, :id)
    end

    # Only allow a list of trusted parameters through.
    def product_product_params
      hash = params.require(:product_product).permit(:name, :description, :price, :product_category_id, :product_type_id, :photos => [])      
      if hash[:price]
        hash[:price] = hash[:price].gsub(",", ".")
      end
      hash
    end
end

app/controllers/admin/product/types_controller.rb
class Admin::Product::TypesController < AdminController
  before_action :set_product_type, only: [:show, :edit, :update, :destroy]

  # GET /product/types
  # GET /product/types.json
  def index
    @product_types = Product::Type.all
  end

  # GET /product/types/1
  # GET /product/types/1.json
  def show
  end

  # GET /product/types/new
  def new
    @product_type = Product::Type.new
  end

  # GET /product/types/1/edit
  def edit
  end

  # POST /product/types
  # POST /product/types.json
  def create
    @product_type = Product::Type.new(product_type_params)

    respond_to do |format|
      if @product_type.save
        format.html { redirect_to @product_type, notice: 'Type was successfully created.' }
        format.json { render :show, status: :created, location: @product_type }
      else
        format.html { render :new }
        format.json { render json: @product_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product/types/1
  # PATCH/PUT /product/types/1.json
  def update
    respond_to do |format|
      if @product_type.update(product_type_params)
        format.html { redirect_to @product_type, notice: 'Type was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_type }
      else
        format.html { render :edit }
        format.json { render json: @product_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product/types/1
  # DELETE /product/types/1.json
  def destroy
    @product_type.destroy
    respond_to do |format|
      format.html { redirect_to product_types_url, notice: 'Type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_type
      @product_type = Product::Type.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_type_params
      params.require(:product_type).permit(:name)
    end
end

app/controllers/admin/product/variations_controller.rb
class Admin::Product::VariationsController < ApplicationController
  before_action :set_product_variation, only: [:show, :edit, :update, :destroy]

  # GET /product/variations
  # GET /product/variations.json
  def index
    @product_variations = Product::Variation.all
  end

  # GET /product/variations/1
  # GET /product/variations/1.json
  def show
  end

  # GET /product/variations/new
  def new
    @product_variation = Product::Variation.new
  end

  # GET /product/variations/1/edit
  def edit
  end

  # POST /product/variations
  # POST /product/variations.json
  def create
    @product_variation = Product::Variation.new(product_variation_params)

    respond_to do |format|
      if @product_variation.save
        format.html { redirect_to @product_variation, notice: 'Variation was successfully created.' }
        format.json { render :show, status: :created, location: @product_variation }
      else
        format.html { render :new }
        format.json { render json: @product_variation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product/variations/1
  # PATCH/PUT /product/variations/1.json
  def update
    respond_to do |format|
      if @product_variation.update(product_variation_params)
        format.html { redirect_to @product_variation, notice: 'Variation was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_variation }
      else
        format.html { render :edit }
        format.json { render json: @product_variation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product/variations/1
  # DELETE /product/variations/1.json
  def destroy
    @product_variation.destroy
    respond_to do |format|
      format.html { redirect_to product_variations_url, notice: 'Variation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_variation
      @product_variation = Product::Variation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_variation_params
      params.require(:product_variation).permit(:name, :description, :price)
    end
end

app/controllers/user/product/categories_controller.rb
class User::Product::CategoriesController < UserController
  skip_before_action :authenticate_user!, only: [:index]
  before_action :set_cart

  def index
    @categories = Product::Category.all
  end  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_category
      @product_category = Product::Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_category_params
      params.require(:product_category).permit(:name)
    end
end

app/controllers/user/product/products_controller.rb
class User::Product::ProductsController < UserController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_product_product, only: [:show, :edit, :update, :destroy]
  before_action :set_cart

  # GET /product/products
  # GET /product/products.json
  def index
    if params[:category]
      @products = Product::Product.where(product_category_id: params[:category])
    else
      @products = Product::Product.all      
    end    
    #@products = Product::Product.all.order(created_at: :desc).paginate(:page => params[:page], :per_page => 10)
  end

  # GET /product/products/1
  # GET /product/products/1.json
  def show
  end  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_product
      @product = Product::Product.find(params[:id])
      if params[:sub_id] && params[:sub_id].to_i > 0
        set_cart
        @product_from_cart = @cart.items.select {|i| i["product_id"] == params[:id].to_i && i["sub_id"] == params[:sub_id].to_i}
      end
    end

    # Only allow a list of trusted parameters through.
    def product_product_params
      params.require(:product_product).permit(:name, :description, :price, :product_category_id, :product_type_id, :photos => [])
    end
end

app/views/admin/product/products/_form.html.slim
div.x_panel
  div.x_content
    = form_for @product_product do |f|
      - if @product_product.errors.any?
        #error_explanation
          h2 = "#{pluralize(@product_product.errors.count, "error")} prohibited this product_product from being saved:"
          ul
            - @product_product.errors.full_messages.each do |message|
              li = message
      
      .row
        .col-md-8
          .form-group
            = f.label "Nome"
            = f.text_field :name, class: "form-control"
        .col-md-4
          .form-group
            = f.label "Preço"
            = f.text_field :price, class: "form-control"    
      .row
        .col-md-12
          .form-group
            = f.label "Descrição"
            = f.text_area :description, class: "form-control", style: "max-height: 100px; min-height: 100px"
      .row
        .col-md-6
          .form-group
            = f.label "Categoria"
            = f.select("product_category_id", @product_categories, {include_blank: false}, class: "form-control")          
        .col-md-6
          .form-group
            = f.label "Tipo"    
            = f.select("product_type_id", @product_types, {include_blank: false}, class: "form-control")
      .row
        .col-md-12
          .form-group
            .row style="padding: 15px"
              - if @product_product.photos.count > 0
                - total = @product_product.photos.count
                - @product_product.photos.each do |photo|
                  - i = 0
                  .col-2 style="height: 250px; border: 1px dashed gray; cursor: pointer"
                      = f.file_field :photos, accept: "image/*", name: "product_product[photos][]", hidden: true, class: "img-input", id: "img_input_#{i}", data: {index: i}
                      = image_tag(photo, size: "16x10", id: "img_ctn_#{i}", class: "img-ctn", data: {index: i} ,style: "width: 100%; height: 100%;")
                - (6 - total).times do |i|
                  .col-2 style="height: 250px; border: 1px dashed gray; cursor: pointer"
                    = f.file_field :photos, accept: "image/*", name: "product_product[photos][]", hidden: true, class: "img-input", id: "img_input_#{i}", data: {index: i}
                    = image_tag("/images/default-image.png", size: "16x10", id: "img_ctn_#{i}", class: "img-ctn", data: {index: i} ,style: "width: 100%; height: 100%;")
              - else      
                - 6.times do |i|
                  .col-2 style="height: 250px; border: 1px dashed gray; cursor: pointer"
                    = f.file_field :photos, accept: "image/*", name: "product_product[photos][]", hidden: true, class: "img-input", id: "img_input_#{i}", data: {index: i}
                    = image_tag("/images/default-image.png", size: "16x10", id: "img_ctn_#{i}", class: "img-ctn", data: {index: i} ,style: "width: 100%; height: 100%;")
          

      .actions = f.submit "Salvar", class: "btn btn-success btn-sm"

= javascript_include_tag "product/products"

javascript:

  jQuery("#product_product_price").keydown(function(e) {
    if ([8].includes(e.keyCode)) {
      return;
    }
    let oldValue = jQuery(this).val();
    let newValue = jQuery(this).val() + e.key;
    if (newValue.match(/^[0-9]+(,?[0-9]*){1}$/g) == null) {
      e.preventDefault();
      jQuery(this).val(oldValue);
    }
  });

  jQuery(".img-input").change(function() {
    let input = jQuery(this);

    if (input[0].files && input[0].files[0]) {        
      var reader = new FileReader();
      
      reader.onload = function(e) {
        $("#img_ctn_" + input.data("index")).attr("src", e.target.result);
      }
      
      reader.readAsDataURL(input[0].files[0]); // convert to base64 string
    }
  });

  jQuery(document).ready(function() {
    jQuery(".img-ctn").click(function() {
      jQuery("#img_input_" + jQuery(this).data("index")).click();
    });    
    
    jQuery("#product_product_price").applyRealMask();
  });

app/views/admin/product/products/edit.html.slim
ul.breadcrumbs
  li  
    a href="#{product_products_path}"
      | Produtos
    span.separator
  li Editar

== render 'form'

=> link_to 'Mostrar', @product_product, id: "btn_mostrar", class: "btn btn-primary btn-sm", style: "display: inline-block"
=< link_to 'Voltar', product_products_path, id: "btn_voltar", class: "btn btn-secondary btn-sm", style: "display: inline-block"

javascript:
    let div = document.getElementsByTagName("form")[0].getElementsByClassName("actions")[0];
    let button1 = document.getElementById("btn_mostrar");
    let button2 = document.getElementById("btn_voltar");
    div.append(button1);
    div.append(button2);

app/views/admin/product/products/index.html.slim
ul.breadcrumbs  
  li Produtos

div.x_panel 
  div.x_title
    = link_to 'Novo produto', new_product_product_path, class: "btn btn-primary btn-sm"  
  div.x_content    
    div.row.table-responsive
      table.table.table-striped.jambo_table.bulk_action
        thead
          tr
            th Id
            th Descrição
            th Sobre
            th Preço
            th Categoria
            th Tipo
            th width="100px"
            th width="100px"
            th width="100px"

        tbody
          - @product_products.each do |product_product|
            tr
              td = product_product.id
              td = product_product.name
              td = product_product.description
              td.td-price = product_product.price
              td = product_product.product_category.name
              td = product_product.product_type.name
              td = link_to 'Mostrar', product_product_path(product_product), class: "btn btn-success btn-sm"
              td = link_to 'Editar', edit_product_product_path(product_product), class: "btn btn-warning btn-sm"
              td = link_to 'Excluir', product_product_path(product_product), data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm", method: :delete
      = my_will_paginate(@product_products).html_safe

= javascript_include_tag "product/products"

javascript:
  jQuery(document).ready(function() {
    jQuery(".img-ctn").click(function() {
      jQuery("#img_input_" + jQuery(this).data("index")).click();
    });    
    
    jQuery(".td-price").applyRealMask();
  });

app/views/admin/product/products/new.html.slim
ul.breadcrumbs
  li  
    a href="#{product_products_path}"
      | Produtos
    span.separator
  li Novo

== render 'form'

= link_to 'Voltar', product_products_path, id:"btn_voltar", class: "btn btn-secondary btn-sm", style: "display: inline-block"

javascript:
  let div = document.getElementsByTagName("form")[0].getElementsByClassName("actions")[0];
  let button = document.getElementById("btn_voltar");
  div.append(button);

app/views/admin/product/products/show.html.slim
ul.breadcrumbs
  li  
    a href="#{product_products_path}"
      | Pacientes
    span.separator
  li Mostrar

div.x_panel
  div.x_content
    p#notice = notice

    .row
        .col-md-8
          .form-group
            label Nome:
            = text_field_tag nil, @product_product.name, class: "form-control", disabled: "disabled"
        .col-md-4
          .form-group
            label Preço:
            = text_field_tag :price, @product_product.price, class: "form-control", disabled: "disabled"
    .row
      .col-md-12
        .form-group
          label Descrição:
          = text_field_tag nil, @product_product.description, class: "form-control", disabled: "disabled"
    .row
      .col-md-6
        .form-group
          label Categoria:
          = text_field_tag nil, @product_product.product_category.name, class: "form-control", disabled: "disabled"
      .col-md-6
        .form-group
          label Tipo:
          = text_field_tag nil, @product_product.product_type.name, class: "form-control", disabled: "disabled"    
    - if @product_product.photos
      .row
        .col-md-12
          .form-group    
            .row
              - @product_product.photos.each do |photo|
                .col-2 style="height: 250px"
                  = image_tag(photo, class: "img-ctn" ,style: "width: 100%; height: 100%; padding: 5px; border: 1px solid red")

      => link_to 'Editar', edit_product_product_path(@product_product), id: "btn_editar", class: "btn btn-primary btn-sm", style: "display: inline-block"
      =< link_to 'Voltar', product_products_path, id: "btn_voltar", class: "btn btn-secondary btn-sm", style: "display: inline-block"

= javascript_include_tag "product/products"

javascript:
  jQuery(document).ready(function() {
    jQuery("#price").applyRealMask();
  });  