config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'
  
  devise_for :admins
  mount_devise_token_auth_for 'User', at: 'users/auth', controllers: {
    sessions: "overrides/sessions",
    registrations: "overrides/registrations"
  }

  scope module: 'admin' do

    resources :user_profiles do
      collection do
        get :send_confirmation_token
      end
    end

    resources :orders do
      collection do
        #post :confirm
        get :confirm
        post :set_status
      end
    end

    namespace :product do
      resources :products
      resources :types
      resources :categories
      resources :complements
      resources :variations
      resources :ingredients
    end
  end

  namespace :user do

    resources :user_profiles
    resources :orders
    resources :addresses

    resources :register do
      collection do        
        post :check_telephone, :check_token, :confirm_token
      end  
    end

    resources :carts do
      collection do        
        post :add, :update_item, :remove, :checkout, :repurchase
      end  
    end

    scope module: 'payment_method' do
      resources :pagarmes
    end

    scope module: 'product' do
      resources :products
      resources :types
      resources :categories
      resources :complements
      resources :variations
      resources :ingredients      
    end
  end

  namespace :home do
    get 'admin/index'
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'inicio', to: 'home/admin#index'
  root to: 'home/admin#index'
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord

    attr_accessor :telephone
    attr_accessor :uid
    attr_accessor :password
    attr_accessor :password_confirmation
    attr_accessor :created_by_admin

    has_many :addresses, dependent: :destroy
    has_one :user, dependent: :destroy
    has_one :cart, dependent: :destroy    
    has_one :payment, dependent: :destroy
    has_one :order_checkout, dependent: :destroy, class_name: "Checkout"
    has_one :order, dependent: :destroy, class_name: "Order"

    validates :name, presence: true

end

app/controllers/admin/user_profiles_controller.rb
class Admin::UserProfilesController < AdminController
  before_action :set_user_profile, only: [:show, :edit, :update, :destroy, :send_confirmation_token]
  before_action :authenticate_admin!

  def send_confirmation_token
    @user.send_confirmation_token
    redirect_to user_profiles_url
  end

  # GET /user_profiles
  # GET /user_profiles.json
  def index
    @user_profiles = UserProfile.all.order(created_at: :desc).paginate(:page => params[:page], :per_page => 10)
  end

  # GET /user_profiles/1
  # GET /user_profiles/1.json
  def show
  end

  # GET /user_profiles/new
  def new
    @user_profile = UserProfile.new    
    @address = Address.new
    @user = User.new
  end

  # GET /user_profiles/1/edit
  def edit    
  end

  # POST /user_profiles
  # POST /user_profiles.json
  def create
    @user_profile = UserProfile.new(user_profile_params)
    @user = User.new(user_profile_params.merge({:provider => "email" ,:email => user_profile_params[:uid]}))
    @address = Address.new(address_params)
    if @user_profile.validate
      if @user.validate
        if @address.validate
          if @user.save && @address.save
            @user_profile = @user.user_profile
            @user_profile.save if @user_profile.address = @address            
            redirect_to @user_profile, notice: 'Paciente criado com sucesso.'
          end
        end
      else
        render :new
      end
    else
      render :new
    end
  end

  # PATCH/PUT /user_profiles/1
  # PATCH/PUT /user_profiles/1.json
  def update
    respond_to do |format|
      if @user_profile.update(user_profile_params) && @address.update(address_params)
        format.html { redirect_to @user_profile, notice: 'User profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_profile }
      else
        format.html { render :edit }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_profiles/1
  # DELETE /user_profiles/1.json
  def destroy
    @user_profile.destroy
    respond_to do |format|
      format.html { redirect_to user_profiles_url, notice: 'User profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_profile
      @user_profile = UserProfile.find(params[:id])
      @user = @user_profile.user
    end

    # Only allow a list of trusted parameters through.
    def user_profile_params
      hash = params.require(:user_profile).permit(:cpf, :password, :password_confirmation, :uid, :email, 
        :name, :genre, :birth_date, :height, :bloodtype, :telephone, :weight, :created_by_admin)
      if hash[:cpf]
        hash[:cpf] = hash[:cpf].gsub(".", "")
        hash[:cpf] = hash[:cpf].gsub("-", "")
      end
      hash
    end

    def address_params
      params.require(:address).permit(:zipcode, :street, :street, :neighborhood, :city, :state, :country)
    end

end

app/controllers/user/user_profiles_controller.rb
class User::UserProfilesController < UserController
  before_action :set_user_profile, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!

  # GET /user_profiles
  # GET /user_profiles.json
  def index
    @user_profiles = UserProfile.all.order(created_at: :desc).paginate(:page => params[:page], :per_page => 10)
  end

  # GET /user_profiles/1
  # GET /user_profiles/1.json
  def show
  end

  # GET /user_profiles/new
  def new
    @user_profile = UserProfile.new    
    @address = Address.new
    @user = User.new
  end

  # GET /user_profiles/1/edit
  def edit    
  end

  # POST /user_profiles
  # POST /user_profiles.json
  def create
    @user_profile = UserProfile.new(user_profile_params)
    @user = User.new(user_profile_params.merge({:provider => "email" ,:email => user_profile_params[:uid]}))
    @address = Address.new(address_params)
    if @user_profile.validate
      if @user.validate
        if @address.validate
          if @user.save && @address.save
            @user_profile = @user.user_profile
            @user_profile.save if @user_profile.address = @address            
            redirect_to @user_profile, notice: 'Paciente criado com sucesso.'
          end
        end
      else
        render :new
      end
    else
      render :new
    end
  end

  # PATCH/PUT /user_profiles/1
  # PATCH/PUT /user_profiles/1.json
  def update
    respond_to do |format|
      if @user_profile.update(user_profile_params) && @address.update(address_params)
        format.html { redirect_to @user_profile, notice: 'User profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_profile }
      else
        format.html { render :edit }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_profiles/1
  # DELETE /user_profiles/1.json
  def destroy
    @user_profile.destroy
    respond_to do |format|
      format.html { redirect_to user_profiles_url, notice: 'User profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_profile
      @user_profile = UserProfile.find(params[:id])
      @user = @user_profile.user
      @address = @user_profile.address
    end

    # Only allow a list of trusted parameters through.
    def user_profile_params
      hash = params.require(:user_profile).permit(:cpf, :password, :password_confirmation, :uid, :email, 
        :name, :genre, :birth_date, :height, :bloodtype, :telephone, :weight, :created_by_admin)
      if hash[:cpf]
        hash[:cpf] = hash[:cpf].gsub(".", "")
        hash[:cpf] = hash[:cpf].gsub("-", "")
      end
      hash
    end

    def address_params
      params.require(:address).permit(:zipcode, :street, :street, :neighborhood, :city, :state, :country)
    end

end

app/views/admin/user_profiles/_form.html.slim
div.x_panel
  div.x_content
    = form_for [@user_profile] do |f|
      = f.text_field :created_by_admin, class: "form-control", hidden: "hidden", value: "true"
      - if @user_profile.errors.any? || @user.errors.any?
        #error_explanation
          - if @user_profile.errors.any?
            ul
              - @user_profile.errors.full_messages.each do |message|
                li = message
          - if @user.errors.any?
              ul
                - @user.errors.full_messages.each do |message|
                  li = message
      - if action_name == "new" || action_name == "create"
        h2 Usuário
        .row
          .col-md-3
            .form-group
              = f.label "Telefone"
              = f.text_field :telephone, class: "form-control"  
          .col-md-3
            .form-group
              = f.label "CPF"
              = f.text_field :cpf, class: "form-control"
          .col-md-6
            .form-group
              = f.label "Email"
              = f.email_field :uid, class: "form-control"
        .row
          .col-md-6
            .form-group
              = f.label "Senha"
              = f.password_field :password, class: "form-control"
          .col-md-6 
            .form-group
              = f.label "Repita a senha"
              = f.password_field :password_confirmation, class: "form-control"
        br    

      h2 Perfil do Usuário
      .row
        .col-md-6
          .form-group
            = f.label "Nome"
            = f.text_field :name, class: "form-control"
        .col-md-3
          .form-group
            = f.label "Gênero"        
            = f.select :genre, [{:d => "Masculino", :v => "m"}, {:d => "Feminino", :v => "f"}].collect {|p| [ p[:d], p[:v] ] }, {include_blank: false}, class: "form-control"
        .col-md-3
          .form-group
            = f.label "Aniversário"
            = f.date_field :birth_date, class: "form-control"

      h2 Endereço  
      = fields_for :address, @address do |ad|
        .row
          .col-md-2
            .form-group
              = ad.label "Cep"
              = ad.text_field :zipcode, class: "form-control"
          .col-md-5
            .form-group
              = ad.label "Rua"
              = ad.text_field :street, class: "form-control"
          .col-md-1
            .form-group
              = ad.label "Número"
              = ad.text_field :number, class: "form-control"
          .col-md-4
            .form-group
              = ad.label "Bairro"
              = ad.text_field :neighborhood, class: "form-control"
        .row
          .col-md-6
            .form-group
              = ad.label "Cidade"
              = ad.text_field :city, class: "form-control"
          .col-md-6
            .form-group
              = ad.label "Estado"
              = ad.text_field :state, class: "form-control"

        
      
      .actions = f.submit "Salvar", class: "btn btn-success btn-sm"

= javascript_include_tag 'user_profiles'      

javascript:
  jQuery("#user_profile_cpf").inputmask({mask : "999.999.999-99", regex : "[0-9]"});
  jQuery("#user_profile_telephone").inputmask({mask : "(99) 9 9999-9999", regex : "[0-9]"});

app/views/admin/user_profiles/edit.html.slim
ul.breadcrumbs
  li  
    a href="#{user_profiles_path}"
      | Pacientes
    span.separator
  li Editar

== render 'form'

=> link_to 'Mostrar', @user_profile, id: "btn_mostrar", class: "btn btn-primary btn-sm", style: "display: inline-block"
=< link_to 'Voltar', user_profiles_path, id: "btn_voltar", class: "btn btn-secondary btn-sm", style: "display: inline-block"

javascript:
    let div = document.getElementsByTagName("form")[0].getElementsByClassName("actions")[0];
    let button1 = document.getElementById("btn_mostrar");
    let button2 = document.getElementById("btn_voltar");
    div.append(button1);
    div.append(button2);

app/views/admin/user_profiles/index.html.slim
ul.breadcrumbs  
  li Usuários

div.x_panel
  div.x_content    
    div.row.table-responsive
      table.table.table-striped.jambo_table.bulk_action
        thead
          tr.headings
            th.column-title Nome
            th.column-title Gênero          
            th.column-title Telefone
            th.column-title Email
            th.column-title width="180px"
            /th.column-title width="100px"
            /th.column-title width="100px"
            th.column-title width="100px"

        tbody
          - @user_profiles.each do |user_profile|
            tr
              td = user_profile.name
              td = user_profile.genre == "m" ? "Masculino" : "Feminino"
              td = user_profile.user.telephone
              td = user_profile.user.email
              - if !user_profile.user.confirmed?
                td = link_to 'Enviar confirmação', send_confirmation_token_user_profiles_path(id: user_profile), class: "btn btn-success btn-sm"
              - else
                td
              /td = link_to 'Mostrar', user_profile, class: "btn btn-success btn-sm"
              /td = link_to 'Editar', edit_user_profile_path(user_profile), class: "btn btn-warning btn-sm"
              td = link_to 'Excluir', user_profile, data: { confirm: 'Are you sure?' }, method: :delete, class: "btn btn-danger btn-sm"
      = my_will_paginate(@medic_profiles).html_safe

app/views/admin/user_profiles/new.html.slim
ul.breadcrumbs
  li  
    a href="#{user_profiles_path}"
      | Pacientes
    span.separator
  li Novo

== render 'form'

= link_to 'Voltar', user_profiles_path, id:"btn_voltar", class: "btn btn-secondary btn-sm", style: "display: inline-block"

javascript:
    let div = document.getElementsByTagName("form")[0].getElementsByClassName("actions")[0];
    let button = document.getElementById("btn_voltar");
    div.append(button);

app/views/admin/user_profiles/show.html.slim
ul.breadcrumbs
  li  
    a href="#{user_profiles_path}"
      | Pacientes
    span.separator
  li Mostrar

div.x_panel
  div.x_content
    p#notice = notice
    h2 Usuário
    .row
      .col-md-3
        .form-group
          label Telefone
          = text_field_tag :telephone, @user_profile.user.telephone, class: "form-control", disabled: "disabled"
      .col-md-3
        .form-group
          label CPF
          = text_field_tag :cpf, @user_profile.cpf, class: "form-control", disabled: "disabled"
      .col-md-6
        .form-group
          label Email
          = text_field_tag :uid, @user_profile.user.uid, class: "form-control", disabled: "disabled"
      br    

    h2 Perfil do Usuário
    .row
      .col-md-6
        .form-group
          label Nome
          = text_field_tag :name, @user_profile.name, class: "form-control", disabled: "disabled"
      .col-md-3
        .form-group
          label Gênero        
          = text_field_tag :genre, @user_profile.genre, class: "form-control", disabled: "disabled"
      .col-md-3
        .form-group
          label Aniversário
          = text_field_tag :birth_date, @user_profile.birth_date, class: "form-control", disabled: "disabled"
      
    br

    h2 Endereço  
    .row
      .col-md-2
        .form-group
          label Cep
          = text_field_tag :zipcode, @user_profile.address.zipcode,  class: "form-control", disabled: "disabled"
      .col-md-5
        .form-group
          label Rua
          = text_field_tag :street, @user_profile.address.street,  class: "form-control", disabled: "disabled"
      .col-md-1
        .form-group
          label Número
          = text_field_tag :number, @user_profile.address.number,  class: "form-control", disabled: "disabled"
      .col-md-4
        .form-group
          label Bairro
          = text_field_tag :neighborhood, @user_profile.address.neighborhood,  class: "form-control", disabled: "disabled"
    .row
      .col-md-6
        .form-group
          label Cidade
          = text_field_tag :city, @user_profile.address.city,  class: "form-control", disabled: "disabled"
      .col-md-6
        .form-group
          label Estado
          = text_field_tag :state, @user_profile.address.state,  class: "form-control", disabled: "disabled"      


    => link_to 'Editar', edit_user_profile_path(@user_profile), id: "btn_editar", class: "btn btn-primary btn-sm", style: "display: inline-block"
    =< link_to 'Voltar', user_profiles_path, id: "btn_voltar", class: "btn btn-secondary btn-sm", style: "display: inline-block"

= javascript_include_tag 'user_profiles'      

javascript:
  jQuery("#cpf").inputmask({mask : "999.999.999-99", regex : "[0-9]"});